// React/src/App.js
import { DetailsView, FileManagerComponent, NavigationPane, Toolbar, Inject } from '@syncfusion/ej2-react-filemanager';
import * as React from 'react';
function App() {
    function onBeforeSend(args) {
        if (args.ajaxSettings) {
          args.ajaxSettings.beforeSend = function (args) {
              args.httpRequest.setRequestHeader('Authorization', 'User1');
          };
        }
    }
    function onBeforeDownload(args) {
        args.useFormPost = false;
        if (args.ajaxSettings) {
            args.ajaxSettings.beforeSend = function (args) {
                args.fetchRequest.headers.append('Authorization', 'User1');
            };
        }
    }
    function onBeforeImageLoad(args) {
        args.useImageAsUrl = false;
        // Check if ajaxSettings are present in the arguments
        if (args.ajaxSettings) {
            (args.ajaxSettings).beforeSend = function (args) {
                // Append Authorization header with value 'User1' to fetchRequest headers
                args.fetchRequest.headers.append('Authorization', 'User1');
            };
        }
    }
    return (<div className="control-section">
        <FileManagerComponent  id="file"
            ajaxSettings = {{
                // Replace the hosted port number in the place of "{port}"
                url:"http://localhost:{port}/api/FileManager/FileOperations",
                downloadUrl:"http://localhost:{port}/api/FileManager/Download",
                uploadUrl:"http://localhost:{port}/api/FileManager/Upload",
                getImageUrl:"http://localhost:{port}/api/FileManager/GetImage"
            }} 
            beforeSend={onBeforeSend.bind(this)} 
            beforeDownload={onBeforeDownload.bind(this)} 
            beforeImageLoad={onBeforeImageLoad.bind(this)}>
                <Inject services={[NavigationPane, DetailsView, Toolbar]}/>
            </FileManagerComponent>
    </div>);
}
export default App;

// Angular/src/app/app.component.ts
import { NgModule } from '@angular/core'
import { BrowserModule } from '@angular/platform-browser'
import { Component } from '@angular/core';
import {
    FileManagerModule, FileManagerAllModule, NavigationPaneService, ToolbarService,
    DetailsViewService, BeforeSendEventArgs, BeforeDownloadEventArgs, BeforeImageLoadEventArgs
} from '@syncfusion/ej2-angular-filemanager';

@Component({
    imports: [FileManagerModule,],
    standalone: true,
    selector: 'app-root',
    providers: [NavigationPaneService, ToolbarService, DetailsViewService],
    template: `<ejs-filemanager id='default-filemanager' [ajaxSettings]='ajaxSettings' (beforeSend)='onBeforeSend($event)' (beforeDownload)='onBeforeDownload($event)' (beforeImageLoad)='onBeforeImageLoad($event)'>
        </ejs-filemanager>`
})
export class AppComponent {
    public hostUrl: string = 'http://localhost:{port}/';
    public ajaxSettings: object = {
        // Replace the hosted port number in the place of "{port}"
        url: this.hostUrl + "api/FileManager/FileOperations",
        downloadUrl: this.hostUrl + "api/FileManager/Download",
        uploadUrl: this.hostUrl + "api/FileManager/Upload",
        getImageUrl: this.hostUrl + "api/FileManager/GetImage"
    };

    onBeforeSend(args: BeforeSendEventArgs): void {
        if (args.ajaxSettings) {
            (args.ajaxSettings as any).beforeSend = function (args: any) {
                args.httpRequest.setRequestHeader('Authorization', 'User1');
            };
        }
    }
    onBeforeDownload(args: BeforeDownloadEventArgs) {
        args.useFormPost = false;
        if (args.ajaxSettings) {
            (args.ajaxSettings as any).beforeSend = function (args: any) {
              args.fetchRequest.headers.append('Authorization', 'User1');
            };
        }       
    }
    onBeforeImageLoad(args: BeforeImageLoadEventArgs): void {
        args.useImageAsUrl = false;
         // Check if ajaxSettings are present in the arguments
        if (args.ajaxSettings) {
            (args.ajaxSettings as any).beforeSend = function (args: any) {
                // Append Authorization header with value 'User1' to fetchRequest headers
                args.fetchRequest.headers.append('Authorization', 'User1');
            };
        }
    }
}


<br>
<br>
<br>
<br>
<br>
<br><div id='container'>

    <ejs-slider id='slider' [value]="30" ></ejs-slider>

</div>
